# Insert a browser to be used in the web scraping process (case insensitive)
# Browsers available: chrome, edge
browser: 'edge'

# Insert user agent
user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0'